main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('calc', views.calc, name='calc'),
]

newlight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-asv-led/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('portfolio/', include('portfolio.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portfolio/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.PortfolioView.as_view(), name='portfolio'),
    path('<slug:slug>/', views.PortfolioDetailView.as_view(), name='portfolio_detail'),
]

portfolio/models.py
from django.db import models
from django.urls import reverse


class Portfolio(models.Model):
    title = models.CharField('Заголовок', max_length=100)
    picture = models.ImageField('Картинка', upload_to='img')
    url = models.SlugField(max_length=160, unique=True,)

    def get_absolute_url(self):
        return reverse('portfolio_detail', kwargs={'slug': self.url})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Портфолио'
        verbose_name_plural = 'Портфолио'


class PortfolioImages(models.Model):
    """фото к портфолио"""
    title = models.CharField("Заголовок", max_length=100, default='')
    image = models.ImageField("Изображение", upload_to="img")
    link = models.ForeignKey(Portfolio, verbose_name="портфолио", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "фото к портфолио"
        verbose_name_plural = "фото к портфолио"

portfolio/views.py
from django.views.generic import ListView, DetailView
from .models import Portfolio


class PortfolioView(ListView):
    model = Portfolio
    queryset = Portfolio.objects.all()
    template_name = 'portfolio/portfolio.html'
    context_object_name = 'item_list'


class PortfolioDetailView(DetailView):
    model = Portfolio
    slug_field = 'url'
    context_object_name = 'detail'

portfolio/templates/portfolio/portfolio.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}Портфолио{% endblock %}

{% block body %}
<div class="container">
<!--    <div class="row">-->
        <div class="col-md-4 col-md-offset-4">
            <div class="brand-jumbotron__desc-inner">
                <h2 class="brand-jumbotron__desc-title">Наши работы</h2>
            </div>
        </div>
        <div class="col-md-10 col-md-offset-1">
            <div class="slider-products">
                {% for port in item_list %}
                    <div class="col-md-12 hover-text-one minimized">
                        <figure class="effect-text-four">
                            <a href="{{ port.get_absolute_url }}">
                                <img src="{{ port.picture.url }}" class="" alt=""/>
                                <figcaption>
                                    <p>{{ port.title }}</p>
                                </figcaption>
                            </a>
                        </figure>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<br>
{% endblock %}

portfolio/templates/portfolio/portfolio_detail.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}Портфолио{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.css"/>

<div class="container text-center">
    <div class="col-12">
      <div class="p-3 details-header_port">{{ detail.title }}</div>
    </div>
</div>

<div class="container">
  <div class="row details-block">
    <div class="col-12">
      <div class="f-carousel" id="myCarousel">
        {% for image in detail.portfolioimages_set.all %}
        <div class="f-carousel__slide details-pictures" data-thumb-src="{{ image.image.url }}">
          <img  alt="" data-lazy-src="{{ image.image.url }}" class="carousel-img"/>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="col-7">

    </div>
  </div>
</div>


  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.umd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.umd.js"></script>
  <script>
    new Carousel(document.getElementById("myCarousel"), {
      // Your custom options
      Dots: false,
      Thumbs: {
        type: "classic",
      },
    }, { Thumbs });
  </script>
{% endblock %}

{% block about %}{% endblock %}