catalog/urls.py
from django.urls import path
from . import views
from .views import CategoryListView, SubCategoryListView, ProductListView, ProductDetailView

urlpatterns = [
    path('', CategoryListView.as_view(), name='category_list'),
    path('<slug:category_slug>/', SubCategoryListView.as_view(), name='subcategory_list'),
    path('<slug:category_slug>/<slug:subcategory_slug>/', ProductListView.as_view(), name='product_list'),
    path('<slug:category_slug>/<slug:subcategory_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),



    # path('', views.CatalogView.as_view(), name='catalog'),
    # path('filter/', views.Filters.as_view(), name='filter'),
    # path('<slug:slug>/', views.CatalogDetailView.as_view(), name='details'),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='home'),
    path('catalog', views.catalog, name='catalog'),
    path('portfolio', views.portfolio, name='portfolio'),
    path('calc', views.calc, name='calc'),
]

newlight/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin-asv-led/', admin.site.urls),
    path('', include('main.urls')),
    path('catalog/', include('catalog.urls')),
    path('portfolio/', include('portfolio.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField('Категория', max_length=150, default='name')
    slug = models.SlugField(max_length=160, unique=True)
    description = models.TextField('описание', default='описание')
    image = models.ImageField('Картинка', upload_to='img', null=True, blank=True)

    class Meta:
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('subcategory_list', kwargs={'category_slug': self.slug})


class SubCategory(models.Model):
    name = models.CharField('Подкатегория', max_length=150, default=True)
    description = models.TextField('Описание', default='описание')
    slug = models.SlugField(max_length=160, unique=True)
    image = models.ImageField('Картинка', upload_to='img', null=True, blank=True)
    category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_list', kwargs={'category_slug': self.category.slug,
                                               'subcategory_slug': self.slug})


class Power(models.Model):
    name = models.CharField('Мощность', max_length=150)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Мощность'
        verbose_name_plural = 'Мощность'


class Kelvin(models.Model):
    name = models.CharField('Цветовая температура, К', max_length=150)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.url

    class Meta:
        verbose_name = 'Цветовая температура'
        verbose_name_plural = 'Цветовые температуры'


class Protection(models.Model):
    name = models.CharField('Степень защиты', max_length=150)
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Степень защиты'
        verbose_name_plural = 'Степени защиты'


class Catalog(models.Model):
    name = models.CharField('Название', max_length=50)
    lamp_type = models.CharField('Тип ламп', max_length=50, default='')
    rass_type = models.CharField('Тип рассеивателя', max_length=30, default='')
    power = models.PositiveSmallIntegerField('Мощность, Вт', default=1)
    svet_potok = models.CharField('Световой поток, Лм', max_length=20)
    temp_sveta = models.ForeignKey(Kelvin, verbose_name='Цветовая температура, К', on_delete=models.SET_NULL, null=True,)
    napruga = models.CharField('Номинальное напряжение, В', max_length=100)
    herz = models.CharField('Номинальная частота, Гц', max_length=100, default='')
    koef_power = models.CharField('Коэффициент мощности', max_length=100, default='')
    koef_ra = models.CharField('Коэффициент цветопередачи, Ra', max_length=100, default='')
    protection = models.ForeignKey(Protection, verbose_name='Степень защиты', on_delete=models.SET_NULL, null=True,)
    coef_puls = models.CharField('Коэффициент пульсации, %', max_length=10)
    usage_temp = models.CharField('Допустимая температура эксплуатации, С', max_length=20, default='')
    size = models.CharField('Габариты', max_length=100)
    tip_mon = models.CharField('Тип монтажа', max_length=30)
    garant = models.CharField('Гарантия', max_length=10)
    image = models.ImageField('Картинка', upload_to='img')
    description = models.TextField('Описание', blank=True, null=True)
    subcategory = models.ForeignKey(SubCategory, related_name='products', on_delete=models.CASCADE)
    slug = models.SlugField(unique=True, blank=True, null=True, db_index=True,)

    def __str__(self):
        return self.name


    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'category_slug': self.subcategory.category.slug,
                                                 'subcategory_slug': self.subcategory.slug,
                                                 'product_slug': self.slug})

    class Meta:
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'


class CatalogImages(models.Model):
    """фото к товару"""
    title = models.CharField("Заголовок", max_length=100, default='')
    image = models.ImageField("Изображение", upload_to="img")
    link = models.ForeignKey(Catalog, verbose_name="Товар", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "фото к товару"
        verbose_name_plural = "фото к товарам"

catalog/views.py
from django.db.models import Q
from django.http import JsonResponse
from django.views import View
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.core.mail import send_mail
from django.conf import settings


from .models import Catalog, Category, Power as PowModel, Protection as ProModel, SubCategory


class CategoryListView(ListView):
    model = Category
    template_name = 'catalog/category_list.html'
    context_object_name = 'categories'
    slug_field = 'slug'
    slug_url_kwarg = 'category_slug'


class SubCategoryListView(ListView):
    model = SubCategory
    template_name = 'catalog/subcategory_list.html'
    context_object_name = 'subcategories'
    slug_field = 'slug'
    slug_url_kwarg = 'category_slug'

    def get_queryset(self):
        # Получаем подкатегории по slug категории
        category_slug = self.kwargs['category_slug']
        return SubCategory.objects.filter(category__slug=category_slug)

    def get_context_data(self, **kwargs):
        # Добавляем категорию в контекст
        context = super().get_context_data(**kwargs)
        category_slug = self.kwargs['category_slug']
        try:
            context['category'] = Category.objects.get(slug=category_slug)
        except Category.DoesNotExist:
            context['category'] = None  # Или перенаправление на 404 страницу
        return context


class ProductListView(ListView):
    model = Catalog
    template_name = 'catalog/product_list.html'
    context_object_name = 'products'
    slug_url_kwarg = 'subcategory_slug'

    def get_queryset(self):
        # Получаем товары по slug подкатегории
        subcategory_slug = self.kwargs['subcategory_slug']
        return Catalog.objects.filter(subcategory__slug=subcategory_slug)

    def get_context_data(self, **kwargs):
        # Добавляем подкатегорию и категорию в контекст
        context = super().get_context_data(**kwargs)
        subcategory_slug = self.kwargs['subcategory_slug']

        try:
            context['subcategory'] = SubCategory.objects.get(slug=subcategory_slug)
            context['category'] = context['subcategory'].category
        except SubCategory.DoesNotExist:
            context['subcategory'] = None  # Или перенаправление на 404 страницу
            context['category'] = None

        return context


class ProductDetailView(DetailView):
    model = Catalog
    template_name = 'catalog/product_detail.html'
    context_object_name = 'detail'
    slug_field = 'slug'  # Поле slug для поиска
    slug_url_kwarg = 'product_slug'  # Имя slug в URL

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        url = request.POST.get('url')

        # Формируем сообщение
        subject = 'Запрос цены на светильник'
        message = (
            f'Имя: {name}.\n\n'
            f'email: {email}.\n\n'
            f'Телефон: {phone}.\n\n'
            f'Светильник: {url}\n\n'
        )
        from_email = settings.DEFAULT_FROM_EMAIL
        recipient_list = ['pasukov.e@yandex.ru']

        try:
            send_mail(
                subject,
                message,
                from_email,
                recipient_list,
                fail_silently=False # Если True, ошибки не будут выводиться
            )
            return JsonResponse({'message': 'Ваш запрос отправлен! Мы свяжемся с вами.'})
        except Exception as e:
            # Если произошла ошибка при отправке
            return JsonResponse({'error': f'Не удалось отправить запрос: {str(e)}'}, status=500)



# class Category:
#
#     def get_category(self):
#         return CatModel.objects.all()
#
#     def get_kelvin(self):
#         return KelModel.objects.all()
#
#     def get_protection(self):
#         return ProModel.objects.all()


# class CatalogView(Category, ListView):
#     model = Catalog
#     queryset = Catalog.objects.all()
#     template_name = 'catalog/catalog.html'
#     context_object_name = 'item_list'


# class CatalogDetailView(DetailView):
#     model = Catalog
#     slug_field = 'url'
#     context_object_name = 'detail'


# class Filters(Category, ListView):
#     template_name = 'catalog/catalog.html'
#     context_object_name = 'item_list'
#
#     def get_queryset(self, *args, **kwargs):
#         min_power = self.request.GET.get('min_power')
#         max_power = self.request.GET.get('max_power')
#
#         my_q = Q()
#         if 'category' in self.request.GET:
#             my_q = Q(category__url__in=self.request.GET.getlist('category'))
#         # if 'temp_sveta' in self.request.GET:
#         #     my_q &= Q(temp_sveta__url__in=self.request.GET.getlist('temp_sveta'))
#         if 'protection' in self.request.GET:
#             my_q &= Q(protection__url__in=self.request.GET.getlist('protection'))
#         if min_power:
#             my_q &= Q(power__gte=int(min_power))
#         if max_power:
#             my_q &= Q(power__lte=int(max_power))
#
#         queryset = Catalog.objects.filter(my_q)
#         return queryset

catalog/templates/catalog/catalog.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}Продукция{% endblock %}

{% block body %}
<script src="/static/main/js/slider-power.js" defer></script>
<script src="/static/main/js/scripts.js"></script>
<script src="https://cdn.jsdelivr.net/npm/handlebars@latest/dist/handlebars.js"></script>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js" integrity="sha512-f0VlzJbcEB6KiW8ZVtL+5HWPDyW1+nJEjguZ5IVnSQkvZbwBt2RfCBY0CBO1PsMAqxxrG4Di6TfsCPP3ZRwKpA==" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/css/bootstrap-slider.css" integrity="sha512-SZgE3m1he0aEF3tIxxnz/3mXu/u/wlMNxQSnE0Cni9j/O8Gs+TjM9tm1NX34nRQ7GiLwUEzwuE3Wv2FLz2667w==" crossorigin="anonymous" />


<section class="product-section">
        <div class="grid-container">
            <div class="col-md-12">
                <h2 class="brand-jumbotron__desc-title">old Продукция</h2>
            </div>
            <div class="col-md-12">
                <div class="slider-products slider-products--latent js-slick--products-latent clearfix">
                    {% for prod in prod_list %}
                    <div  class="slider-products__slide">
                        <a class="product-section__item" href="/catalog/filter/?category={{ prod.url }}">
                            <img src="{{ prod.image.url }}" alt="" class="press__item-img">
                            <div class="product-section__item-heading">{{ prod.name }}</div>
                        </a>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>




        <div class=" container-prod container-main">
            <div class="main-content">
                <div class="col-md-3">
                    <div class="filters-menu">
                        <form action="{% url 'filter' %}" method="get" name="filter" id="filter-form">
                            <div class="filters-menu-block">
                                <div class="filters-menu-heading">
                                        <span>Категория</span>
                                </div>
                                <div class="filters-menu-content">
                                    {% for category in view.get_category %}
                                        <input type="checkbox" class="checked" name="category" value="{{ category.url }}" id="category">
                                            <span>{{ category.name }}</span>
                                        <br>
                                    {% endfor %}
                                </div>
                            </div>


<!--                            NOT USED-->
<!--                            <div class="filters-menu-block">-->
<!--                                <div class="filters-menu-heading">-->
<!--                                        <span>Цветовая температура, К</span>-->
<!--                                </div>-->
<!--                                <div class="filters-menu-content">-->
<!--                                    {% for kelvin in view.get_kelvin %}-->
<!--                                        <input type="checkbox" class="checked" name="temp_sveta" value="{{ kelvin.url }}" id="kelvin">-->
<!--                                            <span>{{ kelvin.name }}</span>-->
<!--                                        <br>-->
<!--                                    {% endfor %}-->
<!--                                </div>-->
<!--                            </div>-->
<!--                            NOT USED END                            -->


<!--                            -->
<!--                            <div class="filters-menu-block">-->
<!--                                <div class="filters-menu-heading">-->
<!--                                        <span>Степень защиты</span>-->
<!--                                </div>-->
<!--                                <div class="filters-menu-content">-->
<!--                                    {% for protection in view.get_protection %}-->
<!--                                        <input type="checkbox" class="checked" name="protection" value="{{ protection.url }}" id="protection">-->
<!--                                            <span>{{ protection.name }}</span>-->
<!--                                        <br>-->
<!--                                    {% endfor %}-->
<!--                                </div>-->
<!--                            </div>-->

<!--                            <div class="filters-menu-block">-->
<!--                                <div class="filters-menu-heading">-->
<!--                                        <span>Мощность, Вт</span>-->
<!--                                </div>-->
<!--                                <div class="input-group">-->
<!--                                        <input type="number" class="form-control" name="min_power" placeholder="От" min="1" id="min_power">-->
<!--                                        <input type="number" class="form-control" name="max_power" placeholder="До" max="9999" id="max_power">-->
<!--                                </div>-->
<!--                            </div>-->
<!--                        <button type="submit" class="btn btn&#45;&#45;first">Найти</button>-->
<!--                        </form>-->
<!--                    </div>-->
<!--        </div>-->
<!--        <div class="col-md-9">-->
<!--            <div class="row main-content-product">-->
<!--                {% if item_list %}-->
<!--                {% for el in item_list %}-->
<!--                <div class="product-card">-->
<!--                    <div class="product-thumb">-->
<!--                        <a href="{{ el.get_absolute_url }}"><img src="{{ el.image.url }}" alt=""></a>-->
<!--                    </div>-->
<!--                    <div class="product-details">-->
<!--                        <div class="product-bottom-details d-flex justify-content-center">-->
<!--                            <h4><a href="{{ el.get_absolute_url }}">{{ el.name }}</a></h4>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                {% endfor %}-->
<!--                {% else %}-->
<!--                    Товары отсутствуют-->
<!--                {% endif %}-->
<!--            </div>-->
<!--        </div>-->
  </div>
</div>
{% endblock %}

catalog/templates/catalog/catalog_detail.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}Подробнее{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.css"/>

<div class="container">
  <div class="row details-block">
    <div class="col-5 container-slider">
      <div class="f-carousel" id="myCarousel">
        {% for image in detail.catalogimages_set.all %}
        <div class="f-carousel__slide details-pictures" data-thumb-src="{{ image.image.url }}">
          <img  alt="" data-lazy-src="{{ image.image.url }}" class="carousel-img"/>
        </div>
        {% endfor %}
      </div>
    </div>
      <div class="col-7 container-description">
      <div class="brand-jumbotron__desc-title details-header">{{ detail.name }}</div>
      <div class="details-description">{{ detail.description }}</div>
        <br>
      <div class="tech">Технические характеристики</div>
      <div class="details-table">
            <table class="table caption-top">
              <tbody>
                <tr>
                  <th>Категория</th>
                  <td>{{ detail.category }}</td>
                </tr>
                <tr>
                <tr>
                  <th>Тип лампы</th>
                  <td>{{ detail.lamp_type }}</td>
                </tr>
                <tr>
                  <th>Тип рассеивателя</th>
                  <td>{{ detail.rass_type }}</td>
                </tr>
                <tr>
                  <th>Мощность</th>
                  <td>{{ detail.power }}</td>
                </tr>
                <tr>
                  <th>Световой поток</th>
                  <td>{{ detail.svet_potok }}</td>
                </tr>
                <tr>
                  <th>Цветовая температура</th>
                  <td>{{ detail.temp_sveta }}</td>
                </tr>
                <tr>
                  <th>Номинальное напряжение</th>
                  <td>{{ detail.napruga }}</td>
                </tr>
                <tr>
                  <th>Номинальная частота</th>
                  <td>{{ detail.herz }}</td>
                </tr>
                <tr>
                  <th>Коэффициент мощности</th>
                  <td>{{ detail.koef_power }}</td>
                </tr>
                <tr>
                  <th>Коэффициент цветопередачи</th>
                  <td>{{ detail.koef_ra }}</td>
                </tr>
                <tr>
                  <th>Степень защиты</th>
                  <td>{{ detail.protection }}</td>
                </tr>
                <tr>
                  <th>Коэффициент пульсации</th>
                  <td>{{ detail.coef_puls }}</td>
                </tr>
                <tr>
                  <th>Допустимая температура эксплуатации</th>
                  <td>{{ detail.usage_temp }}</td>
                </tr>
                <tr>
                  <th>Габариты</th>
                  <td>{{ detail.size }}</td>
                </tr>
                <tr>
                  <th>Тип монтажа</th>
                  <td>{{ detail.tip_mon }}</td>
                </tr>
                <tr>
                  <th>Гарантия</th>
                  <td>{{ detail.garant }}</td>
                </tr>
              </tbody>
            </table>
      </div>
    </div>
  </div>
</div>


  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.umd.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.umd.js"></script>
  <script>
    new Carousel(document.getElementById("myCarousel"), {
      // Your custom options
      Dots: false,
      Thumbs: {
        type: "classic",
      },
    }, { Thumbs });
  </script>
{% endblock %}

{% block about %}{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'main/index.html' %}
{% load static %}
{% block title %}Подробнее{% endblock %}

{% block body %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.css"/>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.css"/>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<div class="container">
  <div class="row details-block">
    <div class="col-5 details-block-img">
        <div class="f-carousel" id="myCarousel">
            {% for image in detail.catalogimages_set.all %}
                <div class="f-carousel__slide details-pictures" data-thumb-src="{{ image.image.url }}">
                    <img  alt="" data-lazy-src="{{ image.image.url }}" class="carousel-img"/>
                </div>
            {% endfor %}
        </div>
    </div>
    <div class="col-7 details-block-description ">
      <div class="brand-jumbotron__desc-title details-header">{{ detail.name }}</div>
      <div class="details-description">{{ detail.description }}</div>
        <br>
      <div class="tech">Технические характеристики</div>
      <div class="details-table">
            <table class="table caption-top">
                <tbody>
                    <tr>
                        <th>Категория</th>
                        <td>{{ detail.subcategory.category.name }}</td>
                    </tr>
                    <tr>
                        <th>Подкатегория</th>
                        <td>{{ detail.subcategory.name }}</td>
                    </tr>
                    <tr>
                        <th>Тип лампы</th>
                        <td>{{ detail.lamp_type }}</td>
                    </tr>
                    <tr>
                        <th>Тип рассеивателя</th>
                        <td>{{ detail.rass_type }}</td>
                    </tr>
                    <tr>
                        <th>Мощность</th>
                        <td>{{ detail.power }}</td>
                    </tr>
                    <tr>
                        <th>Световой поток</th>
                        <td>{{ detail.svet_potok }}</td>
                    </tr>
                    <tr>
                        <th>Цветовая температура</th>
                        <td>{{ detail.temp_sveta.name }}</td>
                    </tr>
                    <tr>
                        <th>Номинальное напряжение</th>
                        <td>{{ detail.napruga }}</td>
                    </tr>
                    <tr>
                        <th>Номинальная частота</th>
                        <td>{{ detail.herz }}</td>
                    </tr>
                    <tr>
                        <th>Коэффициент мощности</th>
                        <td>{{ detail.koef_power }}</td>
                    </tr>
                    <tr>
                        <th>Коэффициент цветопередачи</th>
                        <td>{{ detail.koef_ra }}</td>
                    </tr>
                    <tr>
                        <th>Степень защиты</th>
                        <td>{{ detail.protection }}</td>
                    </tr>
                    <tr>
                        <th>Коэффициент пульсации</th>
                        <td>{{ detail.coef_puls }}</td>
                    </tr>
                    <tr>
                        <th>Допустимая температура эксплуатации</th>
                        <td>{{ detail.usage_temp }}</td>
                    </tr>
                    <tr>
                        <th>Габариты</th>
                        <td>{{ detail.size }}</td>
                    </tr>
                    <tr>
                        <th>Тип монтажа</th>
                        <td>{{ detail.tip_mon }}</td>
                    </tr>
                    <tr>
                        <th>Гарантия</th>
                        <td>{{ detail.garant }}</td>
                    </tr>
                </tbody>
            </table>

            <button class="btn btn--first" id="request-price-btn">Запросить цену</button>
            <!-- Модальное окно -->
        <div id="priceModal" class="modal">
            <div class="modal-content">
                <form id="price-request-form">
                    {% csrf_token %}
                    <span class="close">&times;</span>
                    <div class="text-center">
                        <div class="row calc">
                            <div class="col-6 offset-3 brand-jumbotron__desc-title mb-3">Запрос цены</div>
                            <div class="col-6 offset-3 forma forma-input">
                                <div class="mb-3 row form_label_block">
                                    <label class="col-12 col-form-label">Ваше имя:</label>
                                    <div class="col-sm-12">
                                        <input type="text" id="name" name="name" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 offset-3 forma forma-input">
                                <div class="mb-3 row form_label_block">
                                    <label class="col-12 col-form-label">Ваш email:</label>
                                    <div class="col-sm-12">
                                        <input type="email" id="email" name="email" class="form-control" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-6 offset-3 forma forma-input">
                                <div class="mb-3 row form_label_block">
                                    <label class="col-12 col-form-label">Телефон:</label>
                                    <div class="col-sm-12">
                                        <input type="number" id="phone" name="phone" class="form-control" placeholder="необязательно">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <button class="btn btn--first" type="submit">Отправить запрос</button>
                </form>
            <div id="response-message" class="text-center"></div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/carousel/carousel.thumbs.umd.js"></script>
<script>
    new Carousel(document.getElementById("myCarousel"), {
      // Your custom options
      Dots: false,
      Thumbs: {
        type: "classic",
      },
    }, { Thumbs });
</script>
<script>
    $(document).ready(function() {
        var modal = $('#priceModal');
        var btn = $('#request-price-btn');
        var span = $('.close');

        btn.on('click', function() {
            modal.show();
        });

        span.on('click', function() {
            modal.hide();
        });

        $(window).on('click', function(event) {
            if ($(event.target).is(modal)) {
                modal.hide();
            }
        });

        $('#price-request-form').on('submit', function(event) {
            event.preventDefault();
            var formData = $(this).serialize();
            // Добавляем URL текущей страницы в данные формы
            formData += '&url=' + encodeURIComponent(window.location.href);

            $.ajax({
                url: window.location.href,  // Отправляем запрос на текущий URL
                type: 'POST',
                data: formData,
                success: function(response) {
                    $('#response-message').html('<p>' + response.message + '</p>');
                },
                error: function() {
                    $('#response-message').html('<p>Ошибка при отправке запроса. Попробуйте позже.</p>');
                }
            });
        });
    });
</script>
{% endblock %}
{% block about %}{% endblock %}